import { createHash } from "node:crypto";
import { mkdir } from "node:fs/promises";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { CommandSchema, EventPayloadSchemas } from "../src/index.ts";

const protocolRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const repositoryRoot = resolve(protocolRoot, "../..");
const outputs = {
  protocolTypescript: resolve(protocolRoot, "generated/typescript/protocol.generated.ts"),
  protocolSwift: resolve(protocolRoot, "generated/swift/MamachiProtocol.generated.swift"),
  vscodeTypescript: resolve(repositoryRoot, "apps/vscode/src/generated/protocol.generated.ts"),
  macosSwift: resolve(repositoryRoot, "apps/macos/Sources/Mamachi/Generated/MamachiProtocol.generated.swift"),
} as const;

function stableJson(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(stableJson).join(",")}]`;
  if (value !== null && typeof value === "object") {
    return `{${Object.entries(value)
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([key, child]) => `${JSON.stringify(key)}:${stableJson(child)}`)
      .join(",")}}`;
  }
  return JSON.stringify(value);
}

function prettyStableJson(value: unknown): string {
  return `${JSON.stringify(JSON.parse(stableJson(value)), null, 2)}\n`;
}

function schemaTypeConst(schema: unknown): string | undefined {
  if (schema === null || typeof schema !== "object" || !("properties" in schema)) return undefined;
  const properties = schema.properties;
  if (properties === null || typeof properties !== "object" || !("type" in properties)) return undefined;
  const propertySchema = properties.type;
  if (propertySchema === null || typeof propertySchema !== "object" || !("const" in propertySchema)) return undefined;
  return typeof propertySchema.const === "string" ? propertySchema.const : undefined;
}

const commandVariants = CommandSchema.oneOf;
const commandTypes = commandVariants.map((variant) => {
  const type = schemaTypeConst(variant);
  if (!type) throw new Error("Every canonical command schema must declare a string type const");
  return type;
});
const eventTypes = Object.keys(EventPayloadSchemas);
const schemaDocument = {
  command: CommandSchema,
  eventPayloads: EventPayloadSchemas,
};
const schemaSha256 = createHash("sha256").update(stableJson(schemaDocument)).digest("hex");
const commandSchemaJson = prettyStableJson(CommandSchema);
const eventPayloadSchemasJson = prettyStableJson(EventPayloadSchemas);

function quoteUnion(values: readonly string[]): string {
  return values.map((value) => JSON.stringify(value)).join(" | ");
}

function typescriptBinding(): string {
  return `// Generated by scripts/generate-bindings.ts. Do not edit.\n\nexport const PROTOCOL_ENVELOPE_VERSION = 1 as const;\nexport const PROTOCOL_SCHEMA_SHA256 = ${JSON.stringify(schemaSha256)} as const;\n\nexport const COMMAND_TYPES = ${JSON.stringify(commandTypes, null, 2)} as const;\nexport type CommandType = ${quoteUnion(commandTypes)};\n\nexport const EVENT_TYPES = ${JSON.stringify(eventTypes, null, 2)} as const;\nexport type EventType = ${quoteUnion(eventTypes)};\n\nexport type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };\n\nexport interface CommandEnvelope {\n  id: string;\n  type: CommandType;\n  actor: \"user\" | \"voice\" | \"ui\" | \"vscode\" | \"coder\";\n  expectedRevision: number | null;\n  payload: JsonValue;\n}\n\nexport interface DomainEventEnvelope {\n  version: typeof PROTOCOL_ENVELOPE_VERSION;\n  id: string;\n  seq: number;\n  at: string;\n  type: EventType;\n  actor: \"controller\" | \"policy\" | \"coder\" | \"voice\" | \"ui\" | \"vscode\";\n  projectId?: string;\n  taskId?: string;\n  runId?: string;\n  correlationId: string;\n  causedBy?: string;\n  payload: JsonValue;\n}\n\nexport const COMMAND_SCHEMA = ${commandSchemaJson.trim()} as const;\nexport const EVENT_PAYLOAD_SCHEMAS = ${eventPayloadSchemasJson.trim()} as const;\n`;
}

function swiftIdentifier(value: string): string {
  const words = value.split(/[^A-Za-z0-9]+/).filter(Boolean);
  const joined = words.map((word, index) => {
    const normalized = word.replace(/^[0-9]/, (digit) => `_${digit}`);
    return index === 0 ? normalized[0]!.toLowerCase() + normalized.slice(1) : normalized[0]!.toUpperCase() + normalized.slice(1);
  }).join("");
  const reserved: Record<string, true> = {
    as: true, case: true, default: true, defer: true, do: true, else: true, enum: true,
    extension: true, false: true, for: true, func: true, if: true, import: true, in: true,
    init: true, internal: true, is: true, let: true, nil: true, private: true, protocol: true,
    public: true, repeat: true, return: true, self: true, static: true, struct: true, switch: true,
    throw: true, throws: true, true: true, try: true, typealias: true, var: true, where: true, while: true,
  };
  return reserved[joined] ? `_${joined}` : joined;
}

function swiftCases(values: readonly string[]): string {
  return values.map((value) => `    case ${swiftIdentifier(value)} = ${JSON.stringify(value)}`).join("\n");
}

function swiftStringLiteral(value: string): string {
  let hashes = "#";
  while (value.includes(`\"${hashes}`)) hashes += "#";
  return `${hashes}\"\"\"\n${value.trimEnd()}\n\"\"\"${hashes}`;
}

function swiftBinding(): string {
  return `// Generated by scripts/generate-bindings.ts. Do not edit.\n\nimport Foundation\n\npublic enum MamachiProtocol {\n    public static let envelopeVersion = 1\n    public static let schemaSHA256 = ${JSON.stringify(schemaSha256)}\n    public static let commandSchemaJSON = ${swiftStringLiteral(commandSchemaJson)}\n    public static let eventPayloadSchemasJSON = ${swiftStringLiteral(eventPayloadSchemasJson)}\n}\n\npublic enum MamachiCommandType: String, Codable, CaseIterable, Sendable {\n${swiftCases(commandTypes)}\n}\n\npublic enum MamachiEventType: String, Codable, CaseIterable, Sendable {\n${swiftCases(eventTypes)}\n}\n\npublic indirect enum MamachiJSONValue: Codable, Equatable, Sendable {\n    case null\n    case bool(Bool)\n    case integer(Int64)\n    case number(Double)\n    case string(String)\n    case array([MamachiJSONValue])\n    case object([String: MamachiJSONValue])\n\n    public init(from decoder: Decoder) throws {\n        let container = try decoder.singleValueContainer()\n        if container.decodeNil() { self = .null }\n        else if let value = try? container.decode(Bool.self) { self = .bool(value) }\n        else if let value = try? container.decode(Int64.self) { self = .integer(value) }\n        else if let value = try? container.decode(Double.self) { self = .number(value) }\n        else if let value = try? container.decode(String.self) { self = .string(value) }\n        else if let value = try? container.decode([MamachiJSONValue].self) { self = .array(value) }\n        else if let value = try? container.decode([String: MamachiJSONValue].self) { self = .object(value) }\n        else { throw DecodingError.dataCorruptedError(in: container, debugDescription: \"Unsupported JSON value\") }\n    }\n\n    public func encode(to encoder: Encoder) throws {\n        var container = encoder.singleValueContainer()\n        switch self {\n        case .null: try container.encodeNil()\n        case .bool(let value): try container.encode(value)\n        case .integer(let value): try container.encode(value)\n        case .number(let value): try container.encode(value)\n        case .string(let value): try container.encode(value)\n        case .array(let value): try container.encode(value)\n        case .object(let value): try container.encode(value)\n        }\n    }\n}\n\npublic struct MamachiCommandEnvelope: Codable, Equatable, Sendable {\n    public let id: String\n    public let type: MamachiCommandType\n    public let actor: String\n    public let expectedRevision: Int?\n    public let payload: MamachiJSONValue\n\n    public init(id: String, type: MamachiCommandType, actor: String, expectedRevision: Int?, payload: MamachiJSONValue) {\n        self.id = id\n        self.type = type\n        self.actor = actor\n        self.expectedRevision = expectedRevision\n        self.payload = payload\n    }\n}\n\npublic struct MamachiDomainEventEnvelope: Codable, Equatable, Sendable {\n    public let version: Int\n    public let id: String\n    public let seq: Int\n    public let at: String\n    public let type: MamachiEventType\n    public let actor: String\n    public let projectId: String?\n    public let taskId: String?\n    public let runId: String?\n    public let correlationId: String\n    public let causedBy: String?\n    public let payload: MamachiJSONValue\n}\n`;
}

const typescript = typescriptBinding();
const swift = swiftBinding();
const generated = new Map<string, string>([
  [outputs.protocolTypescript, typescript],
  [outputs.protocolSwift, swift],
  [outputs.vscodeTypescript, typescript],
  [outputs.macosSwift, swift],
]);
const check = process.argv.includes("--check");
const stale: string[] = [];
for (const [path, content] of generated) {
  if (check) {
    const current = await Bun.file(path).exists() ? await Bun.file(path).text() : undefined;
    if (current !== content) stale.push(relative(repositoryRoot, path));
  } else {
    await mkdir(dirname(path), { recursive: true });
    await Bun.write(path, content);
  }
}
if (stale.length > 0) {
  throw new Error(`Generated protocol bindings are stale: ${stale.join(", ")}. Run bun run bindings:generate in packages/protocol.`);
}
if (!check) console.log(`Generated ${generated.size} protocol bindings (${schemaSha256}).`);
